### ISSUE TITLE
I am getting python threading error related to FileChangedEventHandler

### ISSUE THREAD

**Issue by patkoscsaba** [MihaiBalint/dfsync#4]
Watching dir(s): '.'; press [Ctrl-C] to exit

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/.../.venv/lib/python3.9/site-packages/watchdog/observers/api.py", line 199, in run
    self.dispatch_events(self.event_queue, self.timeout)
  File "/home/.../.venv/lib/python3.9/site-packages/watchdog/observers/api.py", line 372, in dispatch_events
    handler.dispatch(event)
  File "/home/.../.venv/lib/python3.9/site-packages/watchdog/events.py", line 282, in dispatch
    self.event_dispatch_map[event.event_type](event)
AttributeError: 'FileChangedEventHandler' object has no attribute 'event_dispatch_map'

**Comment by vladiibine** [comment]
I had a similar issue. What I did was to create a virtualenv with python 3.6.8 installed in it. I installed and ran dfsync from that virtualenv. I don't recall having seen the issue since then.

```
pyenv install 3.6.8
~/.pyenv/versions/3.6.8/bin/python3 -m venv dfsync

source dfsync/bin/activate
dfsync ..... your dfsync flags/opts/args here
```

**Comment by MihaiBalint** [comment]
closing old issue
